database:
  build: ./postgresql

ldap:
  build: ./ldap

smtp-sink:
  build: ./docker/smtp/smtp-sink

courier-imap:
  build: ./docker/smtp/courier-imap
  volumes_from:
    - smtp-sink:rw

webmail:
  build: ./docker/smtp/webmail
  volumes_from:
    - smtp-sink:rw
    
geoserver:
  image: georchestra/geoserver
  volumes:
    - geoserver_datadir:/var/local/geoserver
    
proxy:
  image: georchestra/security-proxy
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
  volumes:
    - ./docker/datadir:/etc/georchestra

cas:
  image: georchestra/cas
  links:
    - ldap
  volumes:
    - ./docker/datadir:/etc/georchestra

mapfishapp:
  image: georchestra/mapfishapp
  links:
    - database
  volumes:
    - ./docker/datadir:/etc/georchestra

extractorapp:
  image: georchestra/extractorapp
  links:
    - database
    - smtp-sink
  volumes:
    - ./docker/datadir:/etc/georchestra

header:
  image: georchestra/header
  volumes:
    - ./docker/datadir:/etc/georchestra

ldapadmin:
  image: georchestra/ldapadmin
  links:
    - database
    - ldap
    - smtp-sink
  volumes:
    - ./docker/datadir:/etc/georchestra

geonetwork:
  image: georchestra/geonetwork
  ports:
    - "1099:1099"
  links:
    - database
    - ldap
  volumes:
    - ./docker/datadir:/etc/georchestra
